name: C++ CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  # --- РАБОТА №1: СБОРКА ПОД LINUX (уже существует) ---
  build-linux: # Дадим ей более конкретное имя
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev libxfixes-dev

    - name: Check out repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build build

    - name: Test
      run: |
        cd build
        ctest --output-on-failure
  
  # --- РАБОТА №2: СБОРКА ПОД WINDOWS (НОВАЯ!) ---
  build-windows:
    # Запускаем на последней версии Windows Server с Visual Studio
    runs-on: windows-latest
    steps:
    # ШАГ 1: Скачиваем код.
    - name: Check out repository
      uses: actions/checkout@v4

    # ШАГ 2: Конфигурируем CMake.
    # Обрати внимание: никаких 'Install dependencies'!
    # Среда Visual Studio, установленная на виртуалке, уже содержит всё нужное для raylib.
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

    # ШАГ 3: Собираем проект.
    - name: Build
      run: cmake --build build

    # ШАГ 4: Запускаем тесты.
    - name: Test
      run: |
        cd build
        ctest --output-on-failure